### ISSUE TITLE
Working with native fetch?

### ISSUE THREAD

**Issue by lox** [gr2m/node-http-recorder#48]
Is this working with native fetch?

I tried the following:

```
fetch('http://httpbin.org/post', {
  method: 'post',
  body: 'data',
})
  .then((response) => response.json())
  .then((data) => console.log(data))
  .catch((error) => console.error(`Fetch error: ${error.message}`))`
```

But didn't see the response recorded.

**Comment by gr2m** [comment]
This will not work, because Node's native `fetch` is coming from [`undici`](https://github.com/nodejs/undici#undicifetchinput-init-promise), and that is built on Node's `net` module, not Node's `http` module which `node-http-recorder` is patching.
